# Generated by Django 5.2.7 on 2025-11-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reason', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='api.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_roster_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100)),
                ('made_league_playoffs', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.league')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UltimatePlayoffEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('playoff_week', models.IntegerField()),
                ('week_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_entries', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('points_scored', models.DecimalField(decimal_places=2, max_digits=5)),
                ('season', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.team')),
            ],
        ),
    ]
