# Generated by Django 5.2.7 on 2025-11-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payout_team_ultimateplayoffentry_weeklyscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='sleeper_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
