# Generated by Django 5.2.7 on 2025-11-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_losses_team_points_for_team_ties_team_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('nfl_team', models.CharField(blank=True, max_length=10, null=True)),
                ('count', models.IntegerField(help_text='How many playoff teams have this player')),
            ],
        ),
    ]
