# Generated by Django 5.2.7 on 2025-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commonplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonplayer',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
