# Generated by Django 5.2.7 on 2025-11-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_commonplayer_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='top_three_players',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
