# Generated by Django 5.2.7 on 2025-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_top_three_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonplayer',
            name='player_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
