# Generated by Django 5.2.7 on 2025-12-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commonplayer_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimateplayoffentry',
            name='conference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
