# Generated by Django 5.2.7 on 2026-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commonplayer_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='sleeper_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
