# Generated by Django 5.2.7 on 2025-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ultimateplayoffentry_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimateplayoffentry',
            name='starting_points',
            field=models.FloatField(default=0.0),
        ),
    ]
